# Generated by Django 6.0.2 on 2026-03-15 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_approved_by_admin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre del usuario')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo del usuario')),
                ('motivo', models.CharField(max_length=200, verbose_name='Motivo de la queja')),
                ('destinatario', models.CharField(choices=[('admin', 'Administrador'), ('seller', 'Vendedor')], max_length=10, verbose_name='A quien va dirigida')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('deadline', models.DateField(verbose_name='Plazo de respuesta')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Resuelta')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario (opcional)')),
            ],
            options={
                'verbose_name': 'Queja',
                'verbose_name_plural': 'Quejas',
                'ordering': ['-created_at'],
            },
        ),
    ]
