# Generated by Django 6.0.2 on 2026-04-22 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_fix_cartitem_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
    ]
