# Generated by Django 6.0.3 on 2026-03-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('delivery', 'Envío a domicilio'), ('pickup', 'Recogida en tienda')], default='pickup', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Efectivo'), ('transfer', 'Transferencia Bancaria'), ('card', 'Tarjeta de Crédito/Débito')], default='cash', max_length=20),
        ),
    ]
