# Generated by Django 6.0.3 on 2026-04-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_days',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('contra_entrega', 'Pago Contra Entrega'), ('transfer', 'Transferencia Bancaria'), ('card', 'Tarjeta de Crédito/Débito')], default='contra_entrega', max_length=20),
        ),
    ]
