# Generated by Django 6.0.3 on 2026-03-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_bank_account_number_order_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='card_holder_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='card_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
