# Generated by Django 6.0.3 on 2026-04-22 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_delivered_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarrantyClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_type', models.CharField(choices=[('no_enciende', 'No enciende'), ('pantalla_rota', 'Pantalla rota/dañada'), ('bateria_mala', 'Batería no dura/carga mal'), ('sonido_malo', 'Sonido defectuoso'), ('botones_no_funcionan', 'Botones no funcionan'), ('wifi_no_funciona', 'WiFi no conecta'), ('touch_no_funciona', 'Touch/no responde'), ('cargador_no_funciona', 'Cargador no funciona'), ('otro', 'Otro problema')], max_length=50)),
                ('damage_description', models.TextField(blank=True, null=True)),
                ('condition_when_received', models.CharField(choices=[('sellado', 'Sellado (sin abrir)'), ('usado_poco', 'Usado poco tiempo'), ('usado_normal', 'Uso normal'), ('mal_uso', 'Mal uso visible')], max_length=50)),
                ('claim_type', models.CharField(choices=[('reemplazo', 'Reemplazo del producto'), ('devolucion', 'Devolución del dinero'), ('reparacion', 'Reparación'), ('descuento', 'Descuento por daño')], max_length=50)),
                ('observations', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranty_claims', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
