# Generated by Django 6.0.2 on 2026-07-02 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_pickup_date_order_pickup_document_and_more'),
        ('users', '0006_alter_complaint_id_alter_userprofile_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderVendorMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_message', to='orders.order')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_vendor_messages', to='users.userprofile')),
            ],
        ),
    ]
