# Generated by Django 6.0.2 on 2026-03-10 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL de la imagen (ej. https://ejemplo.com/imagen.jpg)', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='O subir una imagen desde tu computadora', null=True, upload_to='products/'),
        ),
    ]
