# Generated by Django 6.0.2 on 2026-03-15 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image_url_alter_product_image'),
        ('users', '0003_userprofile_approved_by_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='users.userprofile'),
        ),
    ]
