# Generated by Django 6.0.3 on 2026-03-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_formrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='stock_after',
            field=models.IntegerField(blank=True, help_text='Stock del producto DESPUÉS de este movimiento', null=True),
        ),
    ]
