# Generated by Django 6.0.3 on 2026-04-17 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_formrequest_id_alter_product_id_and_more'),
        ('users', '0006_alter_complaint_id_alter_userprofile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_damaged',
            field=models.BooleanField(default=False, verbose_name='Producto dañado'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_service',
            field=models.BooleanField(default=False, verbose_name='Es un servicio (no tiene stock físico)'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.URLField(blank=True, help_text='URL de la imagen (ej. https://ejemplo.com/imagen.jpg)', null=True)),
                ('image', models.ImageField(blank=True, help_text='O subir una imagen desde tu computadora', null=True, upload_to='services/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='users.userprofile')),
            ],
        ),
    ]
