# Generated by Django 6.0.3 on 2026-04-17 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderitem_product'),
        ('products', '0010_product_is_damaged_product_is_service_service'),
        ('users', '0006_alter_complaint_id_alter_userprofile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('entrada', 'Entrada (Inventario)'), ('salida', 'Salida (Venta)'), ('compra', 'Compra (Cliente)'), ('devolucion', 'Devolución'), ('ajuste', 'Ajuste de Inventario')], max_length=15),
        ),
    ]
