# Generated by Django 6.0.3 on 2026-04-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_stockmovement_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('celular', 'Celulares'), ('tv', 'Televisores'), ('parlante', 'Parlantes'), ('audifonos', 'Audífonos'), ('smartwatch', 'Smartwatches'), ('cargador', 'Cargadores'), ('cable', 'Cables'), ('tablet', 'Tablets'), ('laptop', 'Laptops'), ('accesorio', 'Accesorios'), ('otro', 'Otros')], default='otro', max_length=20, verbose_name='Categoría'),
        ),
    ]
