# Generated by Django 6.0.3 on 2026-04-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0014_supplier_stockmovement_supplier"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockmovement",
            name="supplier",
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="supplier_name",
            field=models.CharField(
                blank=True,
                help_text="Nombre del proveedor validado en DIAN",
                max_length=200,
                verbose_name="Nombre Proveedor",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="supplier_nit",
            field=models.CharField(
                blank=True,
                help_text="NIT del proveedor (validado contra DIAN)",
                max_length=20,
                verbose_name="NIT Proveedor",
            ),
        ),
        migrations.DeleteModel(
            name="Supplier",
        ),
    ]
