# Generated by Django 6.0.3 on 2026-04-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_remove_stockmovement_supplier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifiedSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=15, unique=True, verbose_name='NIT')),
                ('name', models.CharField(max_length=200, verbose_name='Razón Social')),
                ('dv', models.CharField(max_length=2, verbose_name='Dígito de Verificación')),
                ('activity', models.CharField(blank=True, max_length=200, verbose_name='Actividad Económica')),
                ('verified_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Verificación')),
                ('api_source', models.CharField(default='dian_api', max_length=50, verbose_name='Fuente API')),
            ],
            options={
                'verbose_name': 'Proveedor Verificado',
                'verbose_name_plural': 'Proveedores Verificados',
                'ordering': ['-verified_at'],
            },
        ),
    ]
