# Generated by Django 6.0.3 on 2026-04-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_verifiedsupplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifiedsupplier',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='verifiedsupplier',
            name='department',
            field=models.CharField(blank=True, max_length=100, verbose_name='Departamento'),
        ),
    ]
