# Generated by Django 6.0.3 on 2026-04-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_verifiedsupplier_city_verifiedsupplier_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='supplier_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ciudad Proveedor'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='supplier_department',
            field=models.CharField(blank=True, max_length=100, verbose_name='Departamento Proveedor'),
        ),
    ]
