# Generated by Django 6.0.3 on 2026-04-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_stockmovement_supplier_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formrequest',
            name='issue_type',
            field=models.CharField(blank=True, choices=[('pantalla', 'Problema de Pantalla'), ('bateria', 'Batería/Duración'), ('cargador', 'Cargador no funciona'), ('audio', 'Problema de Audio'), ('software', 'Error de Software'), ('botones', 'Botones sin función'), ('wifi', 'Conexión WiFi'), ('touch', 'Touch no responde'), ('Sobrecalentamiento', 'Sobrecalentamiento'), ('Otro', 'Otro problema')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='formrequest',
            name='priority',
            field=models.CharField(choices=[('normal', 'Normal'), ('urgente', 'Urgente'), ('seguimiento', 'Solo Seguimiento')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='formrequest',
            name='service_option',
            field=models.CharField(blank=True, choices=[('revision', 'Revisión Técnica'), ('reparacion', 'Reparación'), ('cambio', 'Cambio de Pieza'), ('mantenimiento', 'Mantenimiento'), ('limpieza', 'Limpieza'), ('garantia', 'Garantía')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='formrequest',
            name='service_type',
            field=models.CharField(choices=[('mantenimiento', 'Mantenimiento/Reparación'), ('venta', 'Venta/Compra Producto'), ('garantia', 'Garantía/Reparación')], max_length=20),
        ),
    ]
