# Generated by Django 6.0.3 on 2026-04-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_formrequest_issue_type_formrequest_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='warranty_details',
            field=models.TextField(blank=True, help_text='Ej: Solo daños de fábrica, no incluye daños físicos', verbose_name='Detalles de la Garantía'),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_months',
            field=models.PositiveIntegerField(choices=[(1, '1 Mes'), (3, '3 Meses'), (6, '6 Meses'), (12, '12 Meses (1 Año)'), (0, 'Sin Garantía')], default=3, verbose_name='Meses de Garantía'),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_type',
            field=models.CharField(choices=[('proveedor', 'Garantía del Proveedor'), ('cliente', 'Garantía del Cliente'), ('ambos', 'Ambos')], default='proveedor', max_length=20, verbose_name='Tipo de Garantía'),
        ),
    ]
