# Generated by Django 6.0.3 on 2026-04-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_product_warranty_details_product_warranty_months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='stock_before',
            field=models.IntegerField(blank=True, help_text='Stock del producto ANTES de este movimiento', null=True),
        ),
    ]
