# Generated by Django 6.0.2 on 2026-06-28 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_stockmovement_stock_before'),
    ]

    operations = [
        migrations.AddField(
            model_name='formrequest',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen adjunta a la solicitud de reparación/mantenimiento', null=True, upload_to='form_requests/'),
        ),
        migrations.AlterField(
            model_name='formrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('reviewed', 'Respondido'), ('completed', 'Solucionado'), ('behavior', 'Comportamiento'), ('rejected', 'Rechazado')], default='pending', max_length=20),
        ),
    ]
