# Generated by Django 6.0.2 on 2026-06-28 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_formrequest_image_alter_formrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('reviewed', 'Respondido'), ('completed', 'Solucionado')], default='pending', max_length=20),
        ),
    ]
