# Generated by Django 6.0.2 on 2026-06-29 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_formrequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencias', models.TextField(blank=True, default='', verbose_name='Referencias')),
                ('especificaciones_tecnicas', models.TextField(blank=True, default='', verbose_name='Especificaciones técnicas')),
                ('caracteristicas', models.TextField(blank=True, default='', verbose_name='Características')),
                ('contenido_caja', models.TextField(blank=True, default='', verbose_name='Contenido de la caja')),
                ('compatibilidades', models.TextField(blank=True, default='', verbose_name='Compatibilidades')),
                ('dimensiones', models.TextField(blank=True, default='', verbose_name='Dimensiones')),
                ('materiales', models.TextField(blank=True, default='', verbose_name='Materiales')),
                ('garantia_detalle', models.TextField(blank=True, default='', help_text='Complementa warranty_details si aplica.', verbose_name='Garantía (detalle adicional)')),
                ('otras_comentarios', models.TextField(blank=True, default='', verbose_name='Otras observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='products.product')),
            ],
        ),
    ]
